name: Node.js CI

on:
 push:
     branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build-frontend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: ./frontend

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - run: npm install
        working-directory: ./frontend

      - run: npm run build
        working-directory: ./frontend
        
      - name: Print directory
        run: tree -d .

      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: frontend-build
      #     path: .
      #     # path: |
      #     #   ./frontend/build

  build-backend:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: gradle
      
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: copyAppJar
          gradle-version: 8.10.1
          
          # Path to the root directory of the build
          build-root-directory: backend  

      - name: Print directory
        run: tree -d .

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-frontend-build
          path: .
          # path: ./testing_system/build/**/testing-system.jar
          
  build-image:
  
    runs-on: ubuntu-latest
  
    needs: 
      - build-backend
      - build-frontend

    steps:
    # - name: Download a frontend artifact
    #   uses: actions/download-artifact@v3
      #   with:
      #     name: frontend-build
      #     path: frontend

      - name: Download a backend and frontend artifacts
        uses: actions/download-artifact@v3
        with:
          name: backend-frontend-build
          path: .

      - name: Print directory
        run: tree -d .

      - name: Display structure of downloaded files
        run: ls -R

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.bk
          push: true
          tags: garrri/aws_test_backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.fknginx
          push: true
          tags: garrri/aws_test_frontend:latest

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.bfk
          push: true
          tags: garrri/aws_test_full_app:latest